name: 'AWS Deploy'
description: 'Deploy applications to AWS using various deployment methods'
inputs:
  aws-region:
    description: 'AWS region to deploy to'
    required: true
    default: 'us-east-1'
  deployment-type:
    description: 'Type of AWS deployment (lambda, ecs, ec2, s3, cloudformation)'
    required: true
  app-name:
    description: 'Application name'
    required: true
  environment:
    description: 'Deployment environment (dev, staging, prod)'
    required: true
  source-directory:
    description: 'Source directory to deploy'
    required: false
    default: '.'
  lambda-function-name:
    description: 'Lambda function name (for lambda deployment)'
    required: false
  ecs-cluster:
    description: 'ECS cluster name (for ECS deployment)'
    required: false
  ecs-service:
    description: 'ECS service name (for ECS deployment)'
    required: false
  s3-bucket:
    description: 'S3 bucket name (for S3 deployment)'
    required: false
  cloudformation-stack:
    description: 'CloudFormation stack name (for CF deployment)'
    required: false

outputs:
  deployment-url:
    description: 'Deployment URL if applicable'
    value: ${{ steps.deploy.outputs.url }}
  deployment-status:
    description: 'Deployment status'
    value: ${{ steps.deploy.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}

    - name: Deploy to Lambda
      if: inputs.deployment-type == 'lambda'
      id: deploy-lambda
      shell: bash
      working-directory: ${{ inputs.source-directory }}
      run: |
        # Package Lambda function
        zip -r function.zip . -x "*.git*" "node_modules/*"
        
        # Update Lambda function
        aws lambda update-function-code \
          --function-name ${{ inputs.lambda-function-name }} \
          --zip-file fileb://function.zip
        
        # Get function URL if exists
        FUNC_URL=$(aws lambda get-function-url-config \
          --function-name ${{ inputs.lambda-function-name }} \
          --query 'FunctionUrl' --output text 2>/dev/null || echo "N/A")
        
        echo "url=$FUNC_URL" >> $GITHUB_OUTPUT
        echo "status=deployed" >> $GITHUB_OUTPUT

    - name: Deploy to S3
      if: inputs.deployment-type == 's3'
      id: deploy-s3
      shell: bash
      working-directory: ${{ inputs.source-directory }}
      run: |
        # Sync files to S3
        aws s3 sync . s3://${{ inputs.s3-bucket }}/ --delete
        
        # Get S3 website URL
        BUCKET_URL="https://${{ inputs.s3-bucket }}.s3-website-${{ inputs.aws-region }}.amazonaws.com"
        
        echo "url=$BUCKET_URL" >> $GITHUB_OUTPUT
        echo "status=deployed" >> $GITHUB_OUTPUT

    - name: Deploy to ECS
      if: inputs.deployment-type == 'ecs'
      id: deploy-ecs
      shell: bash
      run: |
        # Force new deployment
        aws ecs update-service \
          --cluster ${{ inputs.ecs-cluster }} \
          --service ${{ inputs.ecs-service }} \
          --force-new-deployment
        
        # Wait for deployment to complete
        aws ecs wait services-stable \
          --cluster ${{ inputs.ecs-cluster }} \
          --services ${{ inputs.ecs-service }}
        
        echo "url=N/A" >> $GITHUB_OUTPUT
        echo "status=deployed" >> $GITHUB_OUTPUT

    - name: Deploy CloudFormation
      if: inputs.deployment-type == 'cloudformation'
      id: deploy-cf
      shell: bash
      working-directory: ${{ inputs.source-directory }}
      run: |
        # Deploy CloudFormation stack
        aws cloudformation deploy \
          --stack-name ${{ inputs.cloudformation-stack }} \
          --template-file template.yml \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides Environment=${{ inputs.environment }}
        
        # Get stack outputs
        OUTPUTS=$(aws cloudformation describe-stacks \
          --stack-name ${{ inputs.cloudformation-stack }} \
          --query 'Stacks[0].Outputs' --output json)
        
        echo "url=N/A" >> $GITHUB_OUTPUT
        echo "status=deployed" >> $GITHUB_OUTPUT

    - name: Set deployment output
      id: deploy
      shell: bash
      run: |
        case "${{ inputs.deployment-type }}" in
          "lambda")
            echo "url=${{ steps.deploy-lambda.outputs.url }}" >> $GITHUB_OUTPUT
            echo "status=${{ steps.deploy-lambda.outputs.status }}" >> $GITHUB_OUTPUT
            ;;
          "s3")
            echo "url=${{ steps.deploy-s3.outputs.url }}" >> $GITHUB_OUTPUT
            echo "status=${{ steps.deploy-s3.outputs.status }}" >> $GITHUB_OUTPUT
            ;;
          "ecs")
            echo "url=${{ steps.deploy-ecs.outputs.url }}" >> $GITHUB_OUTPUT
            echo "status=${{ steps.deploy-ecs.outputs.status }}" >> $GITHUB_OUTPUT
            ;;
          "cloudformation")
            echo "url=${{ steps.deploy-cf.outputs.url }}" >> $GITHUB_OUTPUT
            echo "status=${{ steps.deploy-cf.outputs.status }}" >> $GITHUB_OUTPUT
            ;;
        esac