name: Docker Build and Push

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  docker:
    uses: adoliveira/gh-actions-workflows-hub/.github/workflows/docker-build-push.yml@v1
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
    with:
      registry: 'ghcr.io'
      image-name: ${{ github.repository }}
      tags: |
        latest
        ${{ github.sha }}
