name: Node.js CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    uses: adoliveira/gh-actions-workflows-hub/.github/workflows/node-lint.yml@v1
    with:
      node-version: '20'
      cache: 'npm'
      lint-command: 'npm run lint'
  
  test:
    uses: adoliveira/gh-actions-workflows-hub/.github/workflows/node-test.yml@v1
    with:
      node-version: '20'
      cache: 'npm'
      test-command: 'npm test'
      enable-coverage: true
  
  build:
    needs: [lint, test]
    uses: adoliveira/gh-actions-workflows-hub/.github/workflows/node-build.yml@v1
    with:
      node-version: '20'
      cache: 'npm'
      build-command: 'npm run build'
