name: 'Docker Build and Push'
description: 'Build and push Docker images to container registry with multi-platform support'
author: 'adoliveira'

inputs:
  registry:
    description: 'Container registry (docker.io, ghcr.io, etc.)'
    required: false
    default: 'ghcr.io'
  image-name:
    description: 'Image name (without registry prefix)'
    required: true
  tags:
    description: 'Image tags (comma-separated)'
    required: false
    default: 'latest'
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password or token'
    required: true
  platforms:
    description: 'Target platforms (comma-separated)'
    required: false
    default: 'linux/amd64,linux/arm64'
  context:
    description: 'Build context path'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  push:
    description: 'Push image to registry'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
