name: Node.js Build

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '20'
      cache:
        description: 'Package manager for caching (npm, yarn, pnpm)'
        required: false
        type: string
        default: 'npm'
      build-command:
        description: 'Build command to run'
        required: false
        type: string
        default: 'npm run build'
      artifact-name:
        description: 'Name for build artifact'
        required: false
        type: string
        default: 'build-output'
      artifact-path:
        description: 'Path to build output for artifact upload'
        required: false
        type: string
        default: 'dist'
      upload-artifact:
        description: 'Upload build artifact'
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: adoliveira/gh-actions-workflows-hub/actions/setup-node-env@v1
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache }}
          install-dependencies: 'true'
      
      - name: Build
        run: ${{ inputs.build-command }}
      
      - name: Upload build artifact
        if: inputs.upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 7
