name: Node.js Test

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '20'
      cache:
        description: 'Package manager for caching (npm, yarn, pnpm)'
        required: false
        type: string
        default: 'npm'
      test-command:
        description: 'Test command to run'
        required: false
        type: string
        default: 'npm test'
      coverage-command:
        description: 'Coverage command to run'
        required: false
        type: string
        default: 'npm run coverage'
      enable-coverage:
        description: 'Enable code coverage'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: adoliveira/gh-actions-workflows-hub/actions/setup-node-env@v1
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache }}
          install-dependencies: 'true'
      
      - name: Run tests
        run: ${{ inputs.test-command }}
      
      - name: Generate coverage report
        if: inputs.enable-coverage
        run: ${{ inputs.coverage-command }}
      
      - name: Upload coverage to Codecov
        if: inputs.enable-coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
